// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-tKlWhDSmmGNdmGSuyj68I8k3QwJ6Cl4',
    appId: '1:814128401098:web:b02cbd98ba8b243dcac233',
    messagingSenderId: '814128401098',
    projectId: 'pbbtest-4b6b7',
    authDomain: 'pbbtest-4b6b7.firebaseapp.com',
    storageBucket: 'pbbtest-4b6b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKMa0s5GwGrEo3REPeKXyZlLv9Xy0cac',
    appId: '1:814128401098:android:58b87e103bb51982cac233',
    messagingSenderId: '814128401098',
    projectId: 'pbbtest-4b6b7',
    storageBucket: 'pbbtest-4b6b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjXa2cHtA-ViJI-1jZqMFrEF-E8lCb4pc',
    appId: '1:814128401098:ios:61e1ec2b1e52ae5fcac233',
    messagingSenderId: '814128401098',
    projectId: 'pbbtest-4b6b7',
    storageBucket: 'pbbtest-4b6b7.firebasestorage.app',
    iosBundleId: 'com.example.ppbtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjXa2cHtA-ViJI-1jZqMFrEF-E8lCb4pc',
    appId: '1:814128401098:ios:61e1ec2b1e52ae5fcac233',
    messagingSenderId: '814128401098',
    projectId: 'pbbtest-4b6b7',
    storageBucket: 'pbbtest-4b6b7.firebasestorage.app',
    iosBundleId: 'com.example.ppbtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-tKlWhDSmmGNdmGSuyj68I8k3QwJ6Cl4',
    appId: '1:814128401098:web:7cec7c6f890e34bdcac233',
    messagingSenderId: '814128401098',
    projectId: 'pbbtest-4b6b7',
    authDomain: 'pbbtest-4b6b7.firebaseapp.com',
    storageBucket: 'pbbtest-4b6b7.firebasestorage.app',
  );
}
